import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'

const Home: NextPage = () => {

  const [titlePage, setTitlePage] = useState('MERN Auth UI')

  return (
    <div>
      <Head>
        <title>{ titlePage }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container mx-auto">
          coba 
        </div>
      </main>
    </div>
  )
}

export default Home
